version: '3'
services:
  bleu-daemon:
    container_name: bleu-daemon
    build: ./bleu-daemon
    ports:
      - "9999:9999"
    depends_on:
      - postgres
    volumes:
      - /absolute/host/path/task:/bleu-daemon/task
      - /absolute/host/path/schema:/bleu-daemon/schema
      - /absolute/host/path/config.docker.toml:/bleu-daemon/config.toml
  bleu-server:
    container_name: bleu-server
    build: ./bleu-server
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    volumes:
      - /absolute/host/path/.env:/bleu-server/.env
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgresql
    ports:
      - "5432:5432"