version: '3'
services:
  cv-daemon:
    container_name: cv-daemon
    build: ./cv-daemon
    ports:
      - "9999:9999"
    depends_on:
      - postgres
    volumes:
      - /absolute/host/path/task:/cv-daemon/task
      - /absolute/host/path/schema:/cv-daemon/schema
      - /absolute/host/path/config.docker.toml:/cv-daemon/config.toml
  cv-server:
    container_name: cv-server
    build: ./cv-server
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    volumes:
      - /absolute/host/path/.env.docker:/cv-server/.env
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgresql
    ports:
      - "5432:5432"
