[ethereum]

[email]
smtp-username="smtp_username"
smtp-password="smtp_password"
smtp-relay="smtp.gmail.com"
from="NoBody <nobody@domain.dev>"
reply-to="NoBody <nobody@domain.dev>"

[telegram]
bot-token="TELEGRAM_BOT_TOKEN"

[postgres]
url="postgres://root:postgresql@localhost:5432/postgres"

[slack]
info="https://hooks.slack.com/services/"
warn="https://hooks.slack.com/services/"
error="https://hooks.slack.com/services/"

[elasticsearch]
url="http://localhost:9200"

[app]
plugin=[]
