[jsonrpc]
host="0.0.0.0"
port=9999

[ethereum]

[email]
smtp-username="smtp_username"
smtp-password="smtp_password"
smtp-relay="smtp.gmail.com"
from="NoBody <nobody@domain.dev>"
reply-to="NoBody <nobody@domain.dev>"

[telegram]
bot-token="TELEGRAM_BOT_TOKEN"

[postgres]
host="localhost"
port="5432"
dbname="postgres"
user="root"
password="postgresql"

[slack]
info="https://hooks.slack.com/services/"
warn="https://hooks.slack.com/services/"
error="https://hooks.slack.com/services/"

[elasticsearch]
url="http://localhost:9200"

[app]
plugin=[]
channel-capacity=1024
